let g:go_fmt_command = "goimports"
" let g:go_fmt_fail_silently = 1
let g:go_def_mode = 'gopls'
let g:go_info_mode = 'gopls'
" let g:go_rename_command = 'gopls'
" let g:go_metalinter_command = 'golangci-lint'
" let g:go_diagnostics_enabled = 0
" let g:go_metalinter_enabled = []
let g:go_fmt_command = "gofmt"
let g:syntastic_go_checkers = ['go', 'golint', 'errcheck']
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_format_strings = 1
" let g:go_auto_type_info = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_generate_tags = 1
" let g:go_null_module_warning = 0
let g:go_echo_command_info = 0
